steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "dockerfile.prod",
        "-t",
        "us-central1-docker.pkg.dev/p-l-r-api/p-l-r-api/p-l-r-api:latest",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/p-l-r-api/p-l-r-api/p-l-r-api:latest",
      ]
